apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
spec:
  replicas: 3
  selector:
    matchLabels:
     app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - image: mohanraj123/mohanvoteapp123:1.01
        name: tomcattrain
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 0.1
            memory: 200Mi
          requests:
            cpu: 0.1
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp-svc
spec:
  selector:
    app: demoapp
  ports:
  - port: 8080
    targetPort: 8080
    
