apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
spec:
  replicas: 3
  selector:
    matchLabels:
     app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      imagePullSecrets:
        - name: mytrainregistrykey
      containers:
      - image: mohanraj123/tomcattrain:9
        name: demoapp
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 0.1
            memory: 200Mi
          requests:
            cpu: 0.1
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp-svc
spec:
  selector:
    app: demoapp
  ports:
  - port: 8080
    targetPort: 8080
    
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mytraining-ingress
spec:
  rules:
  - http:
      paths:
      - path: /myweb
        backend:
          serviceName: demoapp-svc
          servicePort: 8080

---